//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveyer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public int SurveyTaker { get; set; }
        public int Question { get; set; }
        public string Seçim { get; set; }
    
        public virtual Question Question1 { get; set; }
        public virtual SurveyTaker SurveyTaker1 { get; set; }
    }
}
